-- V9__fix_identity_columns.sql — Convierte columnas oid a IDENTITY para BDs existentes donde V1 baseline no se ejecutó
-- Idempotente: solo altera si la columna aún no es identity. Usa bloques DO para evitar errores si ya es identity.

DO $$ BEGIN
  IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name='gensitredireccion' AND column_name='oid' AND is_identity='YES') THEN
    EXECUTE 'ALTER TABLE gensitredireccion ALTER COLUMN oid ADD GENERATED BY DEFAULT AS IDENTITY';
  END IF;
END $$;

DO $$ BEGIN
  IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name='genmodulo' AND column_name='oid' AND is_identity='YES') THEN
    EXECUTE 'ALTER TABLE genmodulo ALTER COLUMN oid ADD GENERATED BY DEFAULT AS IDENTITY';
  END IF;
END $$;

DO $$ BEGIN
  IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name='genarea' AND column_name='oid' AND is_identity='YES') THEN
    EXECUTE 'ALTER TABLE genarea ALTER COLUMN oid ADD GENERATED BY DEFAULT AS IDENTITY';
  END IF;
END $$;

DO $$ BEGIN
  IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name='genpiso' AND column_name='oid' AND is_identity='YES') THEN
    EXECUTE 'ALTER TABLE genpiso ALTER COLUMN oid ADD GENERATED BY DEFAULT AS IDENTITY';
  END IF;
END $$;

DO $$ BEGIN
  IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name='gencargointra' AND column_name='oid' AND is_identity='YES') THEN
    EXECUTE 'ALTER TABLE gencargointra ALTER COLUMN oid ADD GENERATED BY DEFAULT AS IDENTITY';
  END IF;
END $$;

DO $$ BEGIN
  IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name='genusuario' AND column_name='oid' AND is_identity='YES') THEN
    EXECUTE 'ALTER TABLE genusuario ALTER COLUMN oid ADD GENERATED BY DEFAULT AS IDENTITY';
  END IF;
END $$;

DO $$ BEGIN
  IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name='genarchivo' AND column_name='oid' AND is_identity='YES') THEN
    EXECUTE 'ALTER TABLE genarchivo ALTER COLUMN oid ADD GENERATED BY DEFAULT AS IDENTITY';
  END IF;
END $$;

DO $$ BEGIN
  IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name='gendircextenciones' AND column_name='oid' AND is_identity='YES') THEN
    EXECUTE 'ALTER TABLE gendircextenciones ALTER COLUMN oid ADD GENERATED BY DEFAULT AS IDENTITY';
  END IF;
END $$;

DO $$ BEGIN
  IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name='gendircorreo' AND column_name='oid' AND is_identity='YES') THEN
    EXECUTE 'ALTER TABLE gendircorreo ALTER COLUMN oid ADD GENERATED BY DEFAULT AS IDENTITY';
  END IF;
END $$;

DO $$ BEGIN
  IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name='gensolusuario' AND column_name='oid' AND is_identity='YES') THEN
    EXECUTE 'ALTER TABLE gensolusuario ALTER COLUMN oid ADD GENERATED BY DEFAULT AS IDENTITY';
  END IF;
END $$;

DO $$ BEGIN
  IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name='genlogs' AND column_name='oid' AND is_identity='YES') THEN
    EXECUTE 'ALTER TABLE genlogs ALTER COLUMN oid ADD GENERATED BY DEFAULT AS IDENTITY';
  END IF;
END $$;

DO $$ BEGIN
  IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name='comrol' AND column_name='oid' AND is_identity='YES') THEN
    EXECUTE 'ALTER TABLE comrol ALTER COLUMN oid ADD GENERATED BY DEFAULT AS IDENTITY';
  END IF;
END $$;

DO $$ BEGIN
  IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name='compermisos' AND column_name='oid' AND is_identity='YES') THEN
    EXECUTE 'ALTER TABLE compermisos ALTER COLUMN oid ADD GENERATED BY DEFAULT AS IDENTITY';
  END IF;
END $$;

DO $$ BEGIN
  IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name='comrolpermiso' AND column_name='oid' AND is_identity='YES') THEN
    EXECUTE 'ALTER TABLE comrolpermiso ALTER COLUMN oid ADD GENERATED BY DEFAULT AS IDENTITY';
  END IF;
END $$;

DO $$ BEGIN
  IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name='comusuario' AND column_name='oid' AND is_identity='YES') THEN
    EXECUTE 'ALTER TABLE comusuario ALTER COLUMN oid ADD GENERATED BY DEFAULT AS IDENTITY';
  END IF;
END $$;

DO $$ BEGIN
  IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name='comtarsegui' AND column_name='oid' AND is_identity='YES') THEN
    EXECUTE 'ALTER TABLE comtarsegui ALTER COLUMN oid ADD GENERATED BY DEFAULT AS IDENTITY';
  END IF;
END $$;

DO $$ BEGIN
  IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name='comtarcome' AND column_name='oid' AND is_identity='YES') THEN
    EXECUTE 'ALTER TABLE comtarcome ALTER COLUMN oid ADD GENERATED BY DEFAULT AS IDENTITY';
  END IF;
END $$;

DO $$ BEGIN
  IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name='comanuncio' AND column_name='oid' AND is_identity='YES') THEN
    EXECUTE 'ALTER TABLE comanuncio ALTER COLUMN oid ADD GENERATED BY DEFAULT AS IDENTITY';
  END IF;
END $$;

DO $$ BEGIN
  IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name='comtipoanuncio' AND column_name='oid' AND is_identity='YES') THEN
    EXECUTE 'ALTER TABLE comtipoanuncio ALTER COLUMN oid ADD GENERATED BY DEFAULT AS IDENTITY';
  END IF;
END $$;

DO $$ BEGIN
  IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name='comlogroacredi' AND column_name='oid' AND is_identity='YES') THEN
    EXECUTE 'ALTER TABLE comlogroacredi ALTER COLUMN oid ADD GENERATED BY DEFAULT AS IDENTITY';
  END IF;
END $$;

DO $$ BEGIN
  IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name='comanuncioarchivo' AND column_name='oid' AND is_identity='YES') THEN
    EXECUTE 'ALTER TABLE comanuncioarchivo ALTER COLUMN oid ADD GENERATED BY DEFAULT AS IDENTITY';
  END IF;
END $$;

DO $$ BEGIN
  IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name='comtareaarchivo' AND column_name='oid' AND is_identity='YES') THEN
    EXECUTE 'ALTER TABLE comtareaarchivo ALTER COLUMN oid ADD GENERATED BY DEFAULT AS IDENTITY';
  END IF;
END $$;

DO $$ BEGIN
  IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name='comlogroarchivo' AND column_name='oid' AND is_identity='YES') THEN
    EXECUTE 'ALTER TABLE comlogroarchivo ALTER COLUMN oid ADD GENERATED BY DEFAULT AS IDENTITY';
  END IF;
END $$;

DO $$ BEGIN
  IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name='asiforcontin' AND column_name='oid' AND is_identity='YES') THEN
    EXECUTE 'ALTER TABLE asiforcontin ALTER COLUMN oid ADD GENERATED BY DEFAULT AS IDENTITY';
  END IF;
END $$;

DO $$ BEGIN
  IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name='asiforconarchivo' AND column_name='oid' AND is_identity='YES') THEN
    EXECUTE 'ALTER TABLE asiforconarchivo ALTER COLUMN oid ADD GENERATED BY DEFAULT AS IDENTITY';
  END IF;
END $$;

DO $$ BEGIN
  IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name='asiconextern' AND column_name='oid' AND is_identity='YES') THEN
    EXECUTE 'ALTER TABLE asiconextern ALTER COLUMN oid ADD GENERATED BY DEFAULT AS IDENTITY';
  END IF;
END $$;

DO $$ BEGIN
  IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name='innovanalitica' AND column_name='oid' AND is_identity='YES') THEN
    EXECUTE 'ALTER TABLE innovanalitica ALTER COLUMN oid ADD GENERATED BY DEFAULT AS IDENTITY';
  END IF;
END $$;

DO $$ BEGIN
  IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name='genequipodominio' AND column_name='oid' AND is_identity='YES') THEN
    EXECUTE 'ALTER TABLE genequipodominio ALTER COLUMN oid ADD GENERATED BY DEFAULT AS IDENTITY';
  END IF;
END $$;

-- Sincroniza secuencias de identity al MAX(oid) actual para evitar colisiones (usa 1 como mínimo porque secuencia no admite 0)
SELECT setval(pg_get_serial_sequence('gensitredireccion','oid'), GREATEST(1, COALESCE((SELECT MAX(oid) FROM gensitredireccion),1)), true);
SELECT setval(pg_get_serial_sequence('genmodulo','oid'), GREATEST(1, COALESCE((SELECT MAX(oid) FROM genmodulo),1)), true);
SELECT setval(pg_get_serial_sequence('genarea','oid'), GREATEST(1, COALESCE((SELECT MAX(oid) FROM genarea),1)), true);
SELECT setval(pg_get_serial_sequence('genpiso','oid'), GREATEST(1, COALESCE((SELECT MAX(oid) FROM genpiso),1)), true);
SELECT setval(pg_get_serial_sequence('gencargointra','oid'), GREATEST(1, COALESCE((SELECT MAX(oid) FROM gencargointra),1)), true);
SELECT setval(pg_get_serial_sequence('genusuario','oid'), GREATEST(1, COALESCE((SELECT MAX(oid) FROM genusuario),1)), true);
SELECT setval(pg_get_serial_sequence('genarchivo','oid'), GREATEST(1, COALESCE((SELECT MAX(oid) FROM genarchivo),1)), true);
SELECT setval(pg_get_serial_sequence('gendircextenciones','oid'), GREATEST(1, COALESCE((SELECT MAX(oid) FROM gendircextenciones),1)), true);
SELECT setval(pg_get_serial_sequence('gendircorreo','oid'), GREATEST(1, COALESCE((SELECT MAX(oid) FROM gendircorreo),1)), true);
SELECT setval(pg_get_serial_sequence('comanuncio','oid'), GREATEST(1, COALESCE((SELECT MAX(oid) FROM comanuncio),1)), true);
SELECT setval(pg_get_serial_sequence('comtarsegui','oid'), GREATEST(1, COALESCE((SELECT MAX(oid) FROM comtarsegui),1)), true);
SELECT setval(pg_get_serial_sequence('comlogroacredi','oid'), GREATEST(1, COALESCE((SELECT MAX(oid) FROM comlogroacredi),1)), true);
