spring:
  datasource:
    url: jdbc:postgresql://${POSTGRES_HOST:192.168.3.121}:${POSTGRES_PORT:5432}/${POSTGRES_DB:intraicvc_test}
    username: ${POSTGRES_USER:sistemasicvc}
    password: ${POSTGRES_PASSWORD:icvc2024}
    driver-class-name: org.postgresql.Driver
  
  jpa:
    hibernate:
      ddl-auto: validate

  flyway:
    enabled: true
    baseline-on-migrate: true
    baseline-version: 1

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics

  endpoint:
    health:
      show-details: always